theme: jekyll-theme-chirpy

lang: en

timezone: Europe/Paris

title: Tech0ne

tagline: Cyber-Security Student

description: >-
  Cyber security and IT blog.

url: "https://Tech0ne.github.io"

github:
  username: tech0ne

twitter:
  username: such_a_rndm_usr

social:
  name: Tech0ne
  email: This.Is.Tech.0ne@protonmail.com
  links:
    - https://twitter.com/such_a_rndm_usr
    - https://github.com/Tech0ne
    - https://www.linkedin.com/in/cl%C3%A9ment-piasco/
    - https://www.root-me.org/442policeman-436580
    - https://tryhackme.com/r/p/fox.one
    - https://app.hackthebox.com/profile/890457

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode:

cdn:

avatar: "https://github.com/Tech0ne.png"

social_preview_image:

toc: true

comments:
  provider: "giscus"
  giscus:
    repo: "tech0ne/comments"
    repo_id: "R_kgDONu6dUw"
    category: General
    category_id: DIC_kwDONu6dU84CmTo4
    mapping: "pathname"
    strict: "0"
    input_position: "bottom"
    lang: "fr"
    reactions_enabled: "1"

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: false
  cache:
    enabled: false
    deny_paths:

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
